src/Aught/SpaceBundle/Entity/User.php
<?php

namespace Aught\SpaceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="Aught\SpaceBundle\Entity\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class User
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, unique=true)
     * @Assert\NotBlank()
     */
    private $email;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="SpaceLink", mappedBy="user")
     */
    private $spaceLinks;

    /**
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="author")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="Relish", mappedBy="author")
     */
    private $relishes;

    /**
     * @ORM\OneToMany(targetEntity="Image", mappedBy="author")
     */
    private $images;

    public function __construct()
    {
        $this->spaceLinks = new ArrayCollection();
        $this->comments   = new ArrayCollection();
        $this->relishes   = new ArrayCollection();
        $this->images     = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTime();
    }

    public function getAddressLineFormat()
    {
        return $this->getName() ? "{$this->getName()} <{$this->getEmail()}>" : $this->getEmail();
    }

    public function getAddressLineFormatMuddle()
    {
        return $this->getName() ? "{$this->getName()} <{$this->getMuddleMail()}>" : $this->getMuddleMail();
    }

    public function getBestName()
    {
        return $this->getName() ?: $this->getEmail();
    }

    public function getBestNameMuddle()
    {
        return $this->getName() ?: $this->getMuddleMail();
    }

    /**
     * Get the user email with the latter part changed to asterisks
     */
    public function getMuddleMail()
    {
        return preg_replace('/(?<=@).*\./', '****.', $this->getEmail());
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return User
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return User
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return User
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Add spaceLinks
     *
     * @param \Aught\SpaceBundle\Entity\SpaceLink $spaceLinks
     * @return User
     */
    public function addSpaceLink(\Aught\SpaceBundle\Entity\SpaceLink $spaceLinks)
    {
        $this->spaceLinks[] = $spaceLinks;

        return $this;
    }

    /**
     * Remove spaceLinks
     *
     * @param \Aught\SpaceBundle\Entity\SpaceLink $spaceLinks
     */
    public function removeSpaceLink(\Aught\SpaceBundle\Entity\SpaceLink $spaceLinks)
    {
        $this->spaceLinks->removeElement($spaceLinks);
    }

    /**
     * Get spaceLinks
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getSpaceLinks()
    {
        return $this->spaceLinks;
    }

    /**
     * Add comments
     *
     * @param \Aught\SpaceBundle\Entity\Comment $comments
     * @return User
     */
    public function addComment(\Aught\SpaceBundle\Entity\Comment $comments)
    {
        $this->comments[] = $comments;

        return $this;
    }

    /**
     * Remove comments
     *
     * @param \Aught\SpaceBundle\Entity\Comment $comments
     */
    public function removeComment(\Aught\SpaceBundle\Entity\Comment $comments)
    {
        $this->comments->removeElement($comments);
    }

    /**
     * Get comments
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * Add relishes
     *
     * @param \Aught\SpaceBundle\Entity\Relish $relishes
     * @return User
     */
    public function addRelish(\Aught\SpaceBundle\Entity\Relish $relishes)
    {
        $this->relishes[] = $relishes;

        return $this;
    }

    /**
     * Remove relishes
     *
     * @param \Aught\SpaceBundle\Entity\Relish $relishes
     */
    public function removeRelish(\Aught\SpaceBundle\Entity\Relish $relishes)
    {
        $this->relishes->removeElement($relishes);
    }

    /**
     * Get relishes
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getRelishes()
    {
        return $this->relishes;
    }

    /**
     * Add images
     *
     * @param \Aught\SpaceBundle\Entity\Image $images
     * @return User
     */
    public function addImage(\Aught\SpaceBundle\Entity\Image $images)
    {
        $this->images[] = $images;

        return $this;
    }

    /**
     * Remove images
     *
     * @param \Aught\SpaceBundle\Entity\Image $images
     */
    public function removeImage(\Aught\SpaceBundle\Entity\Image $images)
    {
        $this->images->removeElement($images);
    }

    /**
     * Get images
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getImages()
    {
        return $this->images;
    }
}

src/Aught/SpaceBundle/Controller/SpaceController.php
<?php

namespace Aught\SpaceBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;

use Aught\SpaceBundle\Entity\User;
use Aught\SpaceBundle\Entity\Space;
use Aught\SpaceBundle\Entity\Comment;
use Aught\SpaceBundle\Entity\Image;
use Aught\SpaceBundle\Entity\SpaceLink;
use Aught\SpaceBundle\Entity\Email;

use Aught\SpaceBundle\Entity\UserRepository;
use Aught\SpaceBundle\Entity\CommentRepository;
use Aught\SpaceBundle\Entity\RelishRepository;

use Aught\SpaceBundle\Form\Type\ContactType;

class SpaceController extends Controller
{
    /**
     * @Route("/", name="home")
     * @Route("/{_locale}", name="home_lang", requirements={"_locale" = "en|ja"})
     * @Template()
     */
    public function homeAction()
    {
        return array();
    }

    /**
     * @Route("/terms", name="terms")
     * @Route("/{_locale}/terms", name="terms_lang", requirements={"_locale" = "en|ja"})
     * @Template()
     */
    public function termsAction()
    {
        return array();
    }

    /**
     * @Route("/contact", name="contact")
     * @Route("/{_locale}/contact", name="contact_lang", requirements={"_locale" = "en|ja"})
     * @Template()
     */
    public function contactAction(Request $request)
    {
        $form = $this->createForm(new ContactType());

        if ($request->isMethod('POST')) {
            $form->bind($request);

            if ($form->isValid()) {
                $message = \Swift_Message::newInstance()
                    ->setSubject($form->get('subject')->getData())
                    ->setFrom($form->get('email')->getData())
                    ->setTo('us.chrisf@gmail.com')
                    ->setBody(
                        $this->renderView(
                            'AughtSpaceBundle:Space:contact_form_message.html.twig',
                            array(
                                'ip' => $request->getClientIp(),
                                'name' => $form->get('name')->getData(),
                                'message' => $form->get('message')->getData()
                            )
                        )
                    );

                $this->get('mailer')->send($message);

                $request->getSession()->getFlashBag()->add('success', 'Your email has been sent! Thanks!');

                return $this->redirect($this->generateUrl('contact'));
            }
        }

        return array(
            'form' => $form->createView()
        );
    }

    /**
     * @Route("/view/{token}", name="space_view")
     * @Route("/view/{_locale}/{token}", name="space_view_lang", requirements={"_locale" = "en|ja"})
     * @ParamConverter("space", class="AughtSpaceBundle:Space")
     * @Template()
     */
    public function viewAction(Request $request, Space $space)
    {
        $em = $this->getDoctrine()->getManager();

        $space_rep = $this->getDoctrine()->getRepository('AughtSpaceBundle:Space');
        $user_rep = $this->getDoctrine()->getRepository('AughtSpaceBundle:User');
        $participants = $space_rep->findParticipantsBySpaceId($space->getId());

        $author = null;
        foreach ($participants as $user) {
            // The first() is not a mistake. When performing the select with the repo, only one space link
            // (the one corresponding to this space) is left attached
            if ($user->getSpaceLinks()->first()->getRelation() == SpaceLink::RELATION_FROM) {
                $author = $user;
                break;
            }
        }

        // If an email was included in the params of the url, use it as the preferred commenter
        $viewer = null;
        $pref_users = array();
        if ($viewer_email = $request->query->get('v')) {
            $result = $user_rep->findByEmail($viewer_email);
            if ($result) {
                $viewer = reset($result);
                $pref_users[] = $viewer;
            }
        }

        $comment = new Comment();

        $form = $this->createFormBuilder($comment)
            ->add('author', 'entity', array(
                'class' => 'AughtSpaceBundle:User',
                'choices' => $participants,
                'data' => $viewer,
                'preferred_choices' => $pref_users,
                'property' => 'addressLineFormatMuddle',
                'empty_value' => 'Who are you?',
            ))
            ->add('body', 'textarea')
            ->add('submit', 'submit')
            ->getForm();

        $form->handleRequest($request);

        // ctodo Handle POSTed comments for when websockets don't work. Probably need to solve it on the twig side.
        if ($form->isValid()) {
            $comment->setSpace($space);
            $em->persist($comment);
            $em->flush();
            return $this->redirect($this->generateUrl('aught_space_space_view', array('token' => $space->getToken())));
        }

        // Stick URLs for images we stored in S3 into the HTML
        $body = $space->getBody();
        $images = $space->getImages();
        if ($images) {
            $image_key_map = array();
            $storage = $this->get("storageUtils");
            foreach ($images as $image) {
                $content_id = $image->getContentId();
                $url = $storage->getUrl($image->getAwsKey());

                if (preg_match("/cid:{$content_id}/", $body)) {
                    $body = preg_replace("/[\"\']cid:{$content_id}[^\"\']*[\"\']/", "\"{$url}\"", $body);
                } else {
                    // If it doesn't appear in the message, append it to the end
                    $body .= "<img src=\"{$url}\">";
                }
            }
        }

        // Filter out dangerous elements
        $config = \HTMLPurifier_Config::createDefault();
        $purifier = new \HTMLPurifier($config);
        $body = $purifier->purify($body);

        // Obfuscate emails
        $body = preg_replace('/([a-zA-Z0-9._%+-]+@)[a-zA-Z0-9.-]+(\.[a-zA-Z]{2,6})/', '$1****$2', $body);
        $space->setBody($body);

        return $this->render('AughtSpaceBundle:Space:view.html.twig', array(
            'participants' => $participants,
            'author' => $author,
            'space' => $space,
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/_mailparser")
     */
    public function mailParseAction(Request $request)
    {
        // Get mail data from POST
        $data = $request->request->get('data');
        $em = $this->getDoctrine()->getManager();

        $email = new Email($data);
        unset($data);

        $em->transactional(function($em) use($email) {
            $email_utils = $this->get('email_utils')->initWithEmail($email);
            $space = $email_utils->registerSpace($em);
            $em->flush(); // Space id from the database is needed for constructing S3 key for images

            $author     = $email_utils->registerAuthor($em, $space);
            $recipients = $email_utils->registerRecipients($em, $space);
            $images     = $email_utils->registerImages($em, $space, $author);

            $email_utils->sendSpaceOpenedEmail($recipients, $space, $author);
        });

        return new JsonResponse(array('result' => 'success'));
    }

    /**
     * @Route("/_socket")
     */
    public function socketAction(Request $request)
    {
        // Get mail data from POST
        $msg = $request->request->get('data');
        if (empty($msg)) throw new \Exception("Invalid JSON for message!", 1);

        $em = $this->getDoctrine()->getManager();
        $space_rep = $this->getDoctrine()->getRepository('AughtSpaceBundle:Space');

        // Find the space corresponding to the token provided by the message
        $space = $space_rep->findByToken($msg['s']);
        if (!$space) throw new \Exception("No such space!", 1);
        $space = reset($space);

        if (!isset($msg['t'])) {
            throw new \Exception("Invalid message from socket: needs type!", 1);
        }

        // $ret = array();
        $em->transactional(function($em) use($msg, $space, $space_rep) {
            $user_rep = $this->getDoctrine()->getRepository('AughtSpaceBundle:User');
            switch ($msg['t']) {
                // Comment on post
                case 'c':
                    $author  = UserRepository::getAuthorFromSocketMessage($msg, $space, $space_rep, $user_rep);
                    $comment = CommentRepository::createCommentFromSocketMessage($msg, $space, $author, $em);

                    // $purifier = new \HTMLPurifier(\HTMLPurifier_Config::createDefault());
                    // $ret['t'] = 'c';
                    // $ret['n'] = $author->getName();
                    // $ret['e'] = $author->getMuddleMail();
                    // $ret['z'] = $comment->getUpdatedAt();
                    // $ret['m'] = $purifier->purify($comment->getBody());
                    break;

                // Post was relished/derelished
                case 'r':
                    $msg['b'] = $msg['b'] === 'true' ? true : false;

                    $author = UserRepository::getAuthorFromSocketMessage($msg, $space, $space_rep, $user_rep);
                    $relish_rep = $this->getDoctrine()->getRepository('AughtSpaceBundle:Relish');
                    RelishRepository::toggleRelish($space, $author, $em, $relish_rep, $msg['b']);

                    // $ret['t'] = 'r';
                    // $ret['n'] = $author->getName();
                    // $ret['e'] = $author->getMuddleMail();
                    break;

                default:
                    break;
            }
        });

        return new JsonResponse(array('result' => 'success'));
    }
}

src/Aught/SpaceBundle/Resources/views/Space/contact.html.twig
{% extends "AughtSpaceBundle::sidebar_layout.html.twig" %}

{% block main_block_title %}
    <h1>{% trans %}general.contact{% endtrans %}</h1>
{% endblock %}

{% block main_block %}
    {% for label, flashes in app.session.flashbag.all %}
        {% for flash in flashes %}
            <div class="alert-{{ label }}">
                {{ flash }}
            </div>
        {% endfor %}
    {% endfor %}

    <form action="{{ path('contact_lang', {'_locale': app.request.locale}) }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}
        <button type="submit">Send</button>
    </form>
{% endblock %}

src/Aught/SpaceBundle/Resources/views/Space/contact_form_message.html.twig
New message from {{ name }}
Sent from re-fwd.com/contact
IP: {{ ip }}

{{ message|raw }}

src/Aught/SpaceBundle/Resources/views/Space/home.html.twig
{% extends "AughtSpaceBundle::layout.html.twig" %}

{% block content %}
    {% if app.environment == 'prod' %}
        {% set example_page_token = 'home.example_page_token'|trans %}
    {% else %}
        {% set example_page_token = 'gg8t7d2nzgrx' %}
    {% endif %}
    {% set example_page = path('space_view_lang',
        {'token': example_page_token,
        'v': 'home.example_page_user'|trans,
        '_locale': app.request.locale})
    %}
    <div class="sixteen columns">
        <h1 class="remove-bottom" {# style="margin-top: 40px" #}>{% trans %}app.name{% endtrans %}</h1>
        <h5>{% trans %}home.headline{% endtrans %}</h5>
        <hr />
    </div>
    <div class="one-third column">
        <h3>{% trans %}home.what_is_headline{% endtrans %}</h3>
        <p>{% trans %}home.what_is_lead_in{% endtrans %}</p>
        <ul class="square">
          <li>{{ 'home.likes_description'|trans|raw }}</li>
          <li>{{ 'home.comments_description'|trans|raw }}</li>
          <li>{{ 'home.styling_description'|trans({'%example_page%': '<a href="' ~ example_page ~ '">' ~ ('home.example_page_linktext'|trans) ~ '</a>' })|raw }}</li>
        </ul>
    </div>
    <div class="one-third column">
        <h3>{% trans %}home.howto_headline{% endtrans %}</h3>
        <p>{% trans %}home.howto{% endtrans %}</p>
    </div>
    <div class="one-third column">
        <h3>{% trans %}home.interested_headline{% endtrans %}</h3>
        <p>{{ 'home.interested'|trans({'%example_page%': '<a href="' ~ example_page ~ '">' ~ ('home.example_page_linktext'|trans) ~ '</a>' })|raw }}</p>
    </div>
{% endblock %}

src/Aught/SpaceBundle/Resources/views/Space/new.html.twig
{% extends "AughtSpaceBundle::layout.html.twig" %}

{% block title "Form" %}

{% block content %}
    {{ form(form) }}
{% endblock %}

src/Aught/SpaceBundle/Resources/views/Space/terms.html.twig
{% extends "AughtSpaceBundle::sidebar_layout.html.twig" %}

{% block main_block_title %}
    <h2>Re-Fwd Terms and Conditions of Use</h2>
{% endblock %}

{% block main_block %}
    <h3>
        1. Terms
    </h3>

    <p>
        By accessing this web site, you are agreeing to be bound by these
        web site Terms and Conditions of Use, all applicable laws and regulations,
        and agree that you are responsible for compliance with any applicable local
        laws. If you do not agree with any of these terms, you are prohibited from
        using or accessing this site. The materials contained in this web site are
        protected by applicable copyright and trademark law.
    </p>

    <h3>
        2. Disclaimer
    </h3>

    <p>
        The materials on Re-Fwd are provided "as is". [THIS COMPANY] makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, [THIS COMPANY] does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
    </p>

    <h3>
        3. Limitations
    </h3>

    <p>
        In no event shall [THIS COMPANY] or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on [THIS COMPANY]'s Internet site, even if [THIS COMPANY] or an [THIS COMPANY] authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
    </p>
                
    <h3>
        4. Revisions and Errata
    </h3>

    <p>
        The materials appearing on [THIS COMPANY]'s web site could include technical, typographical, or photographic errors. [THIS COMPANY] does not warrant that any of the materials on its web site are accurate, complete, or current. [THIS COMPANY] may make changes to the materials contained on its web site at any time without notice. [THIS COMPANY] does not, however, make any commitment to update the materials.
    </p>

    <h3>
        5. Links
    </h3>

    <p>
        [THIS COMPANY] has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by [THIS COMPANY] of the site. Use of any such linked web site is at the user's own risk.
    </p>

    <h3>
        6. Site Terms of Use Modifications
    </h3>

    <p>
        [THIS COMPANY] may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
    </p>

    <h3>
        7. Governing Law
    </h3>

    <p>
        Any claim relating to Re-Fwd shall be governed by the laws of Japan without regard to its conflict of law provisions.
    </p>

    <p>
        General Terms and Conditions applicable to Use of a Web Site.
    </p>

    <h2>
        Privacy Policy
    </h2>

    <p>
        Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
    </p>

    <ul>
        <li>
            Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
        </li>
        <li>
            We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.
        </li>
        <li>
            We will only retain personal information as long as necessary for the fulfillment of those purposes.
        </li>
        <li>
            We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned.
        </li>
        <li>
            Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.
        </li>
        <li>
            We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
        </li>
        <li>
            We will make readily available to customers information about our policies and practices relating to the management of personal information.
        </li>
    </ul>

    <p>
        We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained.
    </p>
{% endblock %}

src/Aught/SpaceBundle/Resources/views/Space/view.html.twig
{% extends "AughtSpaceBundle::sidebar_layout.html.twig" %}

{% block title "Post by " ~ author.name %}

{% block head %}
    <style type="text/css">
        .like-list li:after {
            content: "{% trans %}space.relish_divider{% endtrans %}";
        }
        .like-list li:nth-last-of-type(2):after {
            content: "{% trans %}space.relish_and{% endtrans %}";
        }
        .loading:before {
            content: url("{{ asset('bundles/aughtspace/images/loading.gif') }}")
        }
    </style>
    <link href="{{ asset('bundles/aughtspace/css/view.css') }}" rel="stylesheet" type="text/css" media="all" />
{% endblock %}

{% block foot_scripts %}
    <script type="text/javascript" src="{{ asset('bundles/aughtspace/js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/aughtspace/js/socket.io.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/aughtspace/js/jquery.hotkeys.js') }}"></script>
    <script type="text/javascript">
        var socketUri = '{% if app.environment == 'prod' %}wss{% else %}ws{% endif %}://{{ srv_domain }}:8443';
        var roomId    = '{{ space.token }}';
        var peopleInfo = {
            {{ author.id }} : { name : '{{ author.name }}', email: '{{ author.muddleMail }}' },
            {% for user in participants %}
                {{ user.id }} : { name : '{{ user.name }}', email: '{{ user.muddleMail }}' },
            {% endfor %}
        };
        var likeButtonText   = '{% trans %}space.relish_button{% endtrans %}';
        var unlikeButtonText = '{% trans %}space.unrelish_button{% endtrans %}';
        var youLikeText      = '{% trans %}space.relish_you{% endtrans %}';
        var likeOthersSingular = '{% trans %}space.n_others_relish_singular{% endtrans %}';
        var likeOthersPlural   = '{% trans %}space.n_others_relish_plural{% endtrans %}';
        var youLikeEndTextSingular = '{% trans %}space.relish_this_singular{% endtrans %}';
        var youLikeEndTextPlural   = '{% trans %}space.relish_this_plural{% endtrans %}';
    </script>
    <script type="text/javascript" src="{{ asset('bundles/aughtspace/js/view.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/aughtspace/js/likes.js') }}"></script>
{% endblock %}

{% block sidebar %}
    <ul>
        <li><a href="#likes">{% trans %}space.relish{% endtrans %}</a></li>
        <li><a href="#chat-box">{% trans %}space.chat{% endtrans %}</a></li>
    </ul>
{% endblock %}

{% block main_block_title %}
    <h1 class="subject-line">{{ space.subject }}</h1>
    <p class="author-line">From: {{ author.addressLineFormatMuddle }}</p>
{% endblock %}

{% block main_block %}
    <div class="mail-body" id="mail-body">
        {{ space.body|raw|nl2br }}
    </div>

    <br>
    <hr class="large">

    <form onsubmit="return false;" id="comment-form">
        {% spaceless %}
        <ul id="likes" class="like-list abbreviated twelve columns">
        {% for relish in space.relishes %}
            <li id="like_id_{{relish.author.id}}">{{ relish.author.name|default(relish.author.muddleMail) }}</li>
        {% endfor %}
        </ul>
        {% endspaceless %}
        <div class="clearfix">
            <div class="three columns">&nbsp;</div>
            <button id="like-btn" class="six columns" href="#">Like</button>
            <div class="three columns">&nbsp;</div>
        </div>

        <h3>{% trans %}space.who_are_you{% endtrans %}</h3>
        {{ form_widget(form.author) }}

        <h3>{% trans %}space.add_comment{% endtrans %}</h3>
        <div class="twelve columns chat-container">
            <div class="chat-box" id="chat-box">
                {% for comment in space.comments %}
                    <div class="row"><div class="two columns alpha user-name" title="{{comment.author.muddleMail}}">{{comment.author.bestNameMuddle}}</div><div class="ten columns omega user-message">{{ comment.body|nl2br }}</div>{# <div style="float:right">({{comment.createdAt|date('H:i:s') }})</div> #}</div>
                {% endfor %}
            </div>
            <div class="row clearfix" style="margin-bottom: 0;">
                {{ form_widget(form.body,   {'attr': {'class': 'nine columns alpha chat-message-field', 'placeholder': 'space.chat.type_message'|trans }}) }}
                {{ form_widget(form.submit, {'attr': {'class': 'two columns omega send-button'}, 'label': 'space.chat.send'|trans}) }}
            </div>
        </div>

    </form>
    <br>
{# ({{comment.createdAt|date('Y-m-d H:i:s') }})#}

{% endblock %}